name: Build and Deploy to NuGet

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0 # Use .NET 9

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore ./src/PackedTables/PackedTables.sln

    # Clean solution
    - name: Clean solution
      run: dotnet clean ./src/PackedTables/PackedTables.sln

    # Ensure artifacts directory exists
    - name: Create artifacts directory
      run: mkdir -p ./artifacts

    # Build the project
    - name: Build
      run: dotnet build ./src/PackedTables/PackedTables.sln --configuration Release --no-restore

    # Run tests
    - name: Run tests
      run: dotnet test ./src/PackedTables.Tests/PackedTables.Tests.csproj --configuration Release --no-build

    # Pack the project
    - name: Pack
      run: dotnet pack ./src/PackedTables/PackedTables.sln --configuration Release --no-build --output ./artifacts

    # Upload artifacts for the deploy job
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: ./artifacts

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Only deploy from the main branch

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0 # Use .NET 9

    # Download artifacts
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: build-artifacts

    # Push the package to NuGet
    - name: Publish to NuGet
      run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json