name: Build and Deploy to NuGet

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0 # Use .NET 8

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore ./PackedTables.sln

    # Clean solution
    - name: Clean solution
      run: dotnet clean ./PackedTables.sln

    # Ensure artifacts directory exists
    - name: Create artifacts directory
      run: mkdir -p ./artifacts

    # Build the project
    - name: Build
      run: dotnet build ./PackedTables.sln --configuration Release --no-restore

    # Run tests
    - name: Run tests
      run: dotnet test ./PackedTables.Tests/PackedTables.Tests.csproj --configuration Release --no-build

    # Pack the project
    - name: Pack
      run: dotnet pack ./PackedTables.sln --configuration Release --no-build --output ./artifacts
            
    - name: Verify artifacts directory
      run: ls -la ./artifacts

    # Push the package to NuGet
    - name: Publish to NuGet
      run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json